# Generated by Django 4.2.20 on 2025-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
